config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users
  #devise_for :users
  get 'cart/index'

  resources :items
  root 'static_pages#home'
  get 'static_pages/home'
  get '/products', to:'static_pages#products'
  get '/services', to:'static_pages#services'
  get '/members', to:'static_pages#members'
  get '/help', to:'static_pages#help'
  get '/about', to:'static_pages#about'
  
  get '/admin', to: 'user#admin_login'
  get '/logout', to: 'user#logout'
  
  get '/cart', to: 'cart#index'
  get '/cart/clear', to: 'cart#clearCart'
  get '/cart/:id', to: 'cart#add'
  
  get '/cart/remove/:id', to: 'cart#remove'
  
  root :to => 'site#home'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  #devise :database_authenticatable, :registerable,
         #:recoverable, :rememberable, :trackable, :validatable
end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :authenticate_user!
  def add
    # get the Id of the product
    id = params[:id]
    # if the cart is already been created, use existing cart else create a blank cart
    if session[:cart]then
      cart = session[:cart]
    else
      session[:cart] = {}
      cart = session[:cart]
    end
    if cart[id] then
      cart[id] = cart[id] + 1
    else
      cart[id] = 1
    end
    redirect_to :action => :index
  end
  def clearCart
    session[:cart] = nil
    redirect_to :action => :index
  end
    def index
      if session[:cart] then
        @cart = session[:cart]
      else
        @cart = {}
      end
      def remove
        id = params[:id]
        cart = session[:cart]
        cart.delete id
        
        redirect_to :action => :index
      end
      
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:title, :description, :image_url)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @item = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :description, :price, :image_url, :category, :brand, :quantity)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @categories = Category.all
  end

  def product
  end

  def services
  end

  def members
  end

  def about
  end

  def help
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
    def login
    end
    def admin_login
        session[:login] = 1
        session[:cart] = nil
        flash[:notice] = "Admin Login Successfull!!"
        redirect_to :controller => :items
        
    end
    
    def logout
        session[:login] = nil
        session[:cart] = nil
        flash[:notice] = "You have been successfully logged out!!"
        redirect_to :controller => :items
    end
        
    
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/cart/index.html.erb
<h1>Your Cart</h1>
<br><br> <!-- breaks added just to style the document -->
<% if @cart.empty? %>
    <p> Your cart is empty</p>
<%end%>

<% total = 0 %>

<table class="cart">
    <tr>
        <td class="legend"></td>
        <td class="legend">Item</td>
        <td class="legend">Option</td>
        <td class="legend">Price</td>
        <td class="legend">Qty</td>
        <td class="legend">Total</td>
    </tr>
    
    <% @cart.each do |id,quantity| %>
    <% item = Item.find_by_id(id) %>
    <tr>
        <td>
            <div class="image">
                <%= link_to (image_tag item.image_url, :style => "height:40px"), item %>
            </div>
        </td>
        <td class="title"><%= link_to item.title, item %></td>
        <td><a href="/cart/remove/<%= item.id%>">Remove From Cart</a></td>
        <td class="price"><%=number_to_currency(item.price)%></td>
        <td class="quantity"><%= quantity %></td>
        <td class="price"><%= number_to_currency(quantity * item.price, :unit => "€") %></td>
    </tr>
    <% total += quantity * item.price%>
    <% end %>
    <tr>
        <td colspan="5">
            <div class="total">Total:</div>
        </td>
        <td>
            <div class="price">
                <%= number_to_currency(total, :unit => "Eur")%>
            </div>
        </td>
    </tr>
    </table>
    <p>
        
        
        <%= link_to "Continue Shopping", :controller => :items %>
        <%= link_to 'Clear Cart', :controller => "cart", :action => "clearCart" %>
    </p>

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :category_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :category_description %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url, id: :category_image_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Image url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.title %></td>
        <td><%= category.description %></td>
        <td><%= category.image_url %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @category.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @category.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @category.image_url %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :item_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :item_description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :item_price %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url, id: :item_image_url %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category, id: :item_category %>
  </div>

  <div class="field">
    <%= form.label :brand %>
    <%= form.text_field :brand, id: :item_brand %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity, id: :item_quantity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Products Catalog</h1>
<br>

<table class="catalog">
  <% @item.each do |item| %>
  <thead>
      <tr>
        <td>
          <div class="image">
            <%= link_to (image_tag item.image_url, :style => "height:100px"), item %>
          </div>
          <div class="title">
            <%= link_to item.title, item %>
          </div>
          <div class="description">
            <%= item.description %>
          </div>
          <div class="price">
            <%= number_to_currency(item.price, :unit => "€") %>
          </div>
      <div class="links">
        <% if user_signed_in? %>
          <%= link_to 'Edit', edit_item_path(item) %>
          <%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %>
          <%else%>
          <a href="/cart/<%= item.id %>">Add to Cart></a>
          <%end%>
        </div>
        </td>
      </tr>
    <% end %>
</table>

<br>
<% if user_signed_in? %>
<p>
  <%= link_to 'New Item', new_item_path %></p>
<%end%>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @item.image_url %>
</p>

<p>
  <strong>Category:</strong>
  <%= @item.category %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @item.brand %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @item.quantity %>
</p>
<a href="/cart/<%= @item.id %>"> Add To Cart</a>
<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/_categories.html.erb
<h1> Categories</h1>
<br>
<table class="catalog">
    <% @categories.each do |category| %>
    <tr>
        <td>
            <div class="category">
                <h2><%= category.title %></h2>
                <p><%= category.description%></p>
                
                
            </div>
        </td>
    </tr>
    <% end %>
</table>

app/views/layouts/_footer.html.erb
<div id='footer'>
  <h6 class="footertext">&copy; Online Dream PC Store &trade;</h6>
</div>

app/views/layouts/_header.html.erb
<div id='header'>
    </div>
    <div id='menue'>
        <div id='navbar'>'
    
          <ul> 
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Products", items_path %></li>
            <li><%= link_to "Services", services_path %></li>
            <li><%= link_to "Members", members_path %></li>
            <li><%= link_to "Help", help_path %></li>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Cart", cart_path %></li>
            <li><%= link_to "Log in", admin_path %></li>
            <li><%= link_to "Log out", logout_path %></li>
            
        </ul>
     </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | DreamPC</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header'%>
    <div id='container'>
      <div id='content'>
        <p class="notice"><%= flash[:notice] %></p>
    <%= yield %>
  </div>
  <div id='first column'>
    <div class="loginbox">
      
      <% if user_signed_in? %>
      
      <div>Signed in as.. <%= current_user.email %>(<%= link_to 'Sign out', destroy_user_session_path, :method => :delete %>)</div> 
      <%= link_to 'Edit Profile', edit_user_registration_path %>
      <% else %>
      
      <%= link_to 'Become a Member', new_user_registration_path %> or <%= link_to 'Sign In', new_user_session_path %>
      
      <%end%>
      
      <h2 class="BoxHeaders">Login here...</h2>
      </div>
    </div>
    <div id='searchbox'>
      <h2 class="BoxHeaders">
      <%= link_to 'New Category', new_category_path %>
      </h2>
      </div>
    </div>
    <%= render 'layouts/footer'%>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  <h1>DramPC is a wholesale online store for custom build computers</h1>
  <h2> Contacts US: Tel No. +353 (0) 860871111</h2>
  <h2> Contacts US: Email: info@dreampc.ie (example only)</h2>
  
  </p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  <h2> Information page for direct help</h2>
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
<% provide(:title, "Home") %>
<h1>Home</h1>
<p>
  <h2>Welcome to our DreamPC store, "WHERE DREAMS CAN COME TRUE"</hs>
  
  <h2>You deside what you want and we will put it all together for you</h2>
  
  <h2>..............Enjoy making your dream come true...................</h2>
  
     <h2> ...................Under Development.....................</h2>
  
  
  </h2>
</p>

</div>
<%= image_tag("Welcome.jpg", alt:"Welcome Logo")%> 
<%= render 'layouts/categories' %>

app/views/static_pages/members.html.erb
<% provide(:title, "Members") %>
<h1>Members</h1>
<p>
  <h2> To be developed for members only area.</h2>
  <h2> Payment schedules with payment plans</h2>
  <h2> Progress of build, Upates</h2>
</p>
<%= image_tag("107 towers.jpg", alt:"Sample Tower")%> 

app/views/static_pages/product.html.erb
<% provide(:title, "Members") %>
<h1>Products</h1>
<p>
  The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
  Tutorial</em></a> is a
  <a href="http://www.railstutorial.org/book">book</a> and
  <a href="http://screencasts.railstutorial.org/">screencast series</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
</p>

app/views/static_pages/products.html.erb
<% provide(:title, "Products") %>
<h1>Products</h1>
<p>
  The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
  Tutorial</em></a> is a
  <a href="http://www.railstutorial.org/book">book</a> and
  <a href="http://screencasts.railstutorial.org/">screencast series</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
</p>

app/views/static_pages/services.html.erb
<% provide(:title, "Services") %>
<h1>Services</h1>
<p>
  <h2> This page was to have list of services we offer</h2>
  
</p>